### ISSUE TITLE
XML_Toolkit: Fix Construction

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#358] opened 2019-10-01 18:20 UTC
#### Description:

Current defult settings are out of range for valid construction
`   ..... Last severe error=<root>[Material][Air Barrier - Air Infiltration Barrier][specific_heat] - "0.100000" - Expected number greater than or equal to 100.000000`

![image](https://user-images.githubusercontent.com/26113670/65988868-9186fb00-e480-11e9-9f12-e6de5296efde.png)

#### How to replicate:

run script

#### Test file(s):

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue358_Construction?csf=1&e=HbjegC)

**Comment by FraserGreenroyd** [comment] 2019-10-01 18:21
Where is the default value set? That seems odd that we would have used a default not prescribed by the 6.01 schema?

**Comment by michaldengusiak** [comment] 2019-10-01 18:22
hmm this is pure pull  Analytical from Revit... 
yes, I think we fix this long time ago not sure why this is back...

**Comment by FraserGreenroyd** [comment] 2019-10-01 18:24
Ok so it might be something we need to fix on the engine or possibly Revit or oM side if it's a default object issue. If it's a default XML object then that would be fixed here - could you take a look and see what the default is for the base oM gas fragment (and maybe solid fragment as well) for Environment oM?

**Comment by michaldengusiak** [comment] 2019-10-01 18:33
yes, detail investigation will be needed as I can see unusual values, now even some infinitive values.


```
ERROR: The 'http://www.gbxml.org/schema:U-value' element is invalid - The value '∞' is invalid according to its datatype 'Decimal' - The string '∞' is not a valid Decimal value. Line Position 41 Line Number: 59858

ERROR: The 'http://www.gbxml.org/schema:U-value' element is invalid - The value 'NaN' is invalid according to its datatype 'Decimal' - The string 'NaN' is not a valid Decimal value. Line Position 43 Line Number: 60033

ERROR: 'openingf97f7' is already used as an ID. Line Position 94 Line Number: 54953
```

![image](https://user-images.githubusercontent.com/26113670/65989519-c8114580-e481-11e9-86e6-3bf396ead8cd.png)

apart from this file is 6.01 schema valid

**Comment by FraserGreenroyd** [comment] 2019-10-01 18:34
Well that is odd... let's put this on the to-do list next week - possibly something @Majalindroth could assist with in resolving if we can get to the bottom of the root cause.

**Closed** 2019-10-31 11:36 UTC
Labels: type:bug
