### ISSUE TITLE
XML_Toolkit: Missing Levels in gbXML

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#309] opened 2019-06-28 14:14 UTC
we are missing some Levels/Storeys from gbXML and thfore spaces are assign to wrong Levels

BHoM
![image](https://user-images.githubusercontent.com/26113670/60348378-51af0400-99b7-11e9-92ad-43a2a5ee5343.png)
Revit
![image](https://user-images.githubusercontent.com/26113670/60348392-57a4e500-99b7-11e9-8b79-94f5b91cc378.png)

we have:
![image](https://user-images.githubusercontent.com/26113670/60348539-af435080-99b7-11e9-83d8-5a6b0b211aa1.png)
should be:
![image](https://user-images.githubusercontent.com/26113670/60348655-f2052880-99b7-11e9-917c-8aeb4f3473c3.png)

test standard gbXML export file for any SAM Template

**Comment by FraserGreenroyd** [comment] 2019-06-28 14:20
Can you provide your topologic test file as well please so I can confirm it isn't an issue with the gbXML file itself

**Comment by michaldengusiak** [comment] 2019-06-28 14:25
[test script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue309_MissingLevels?csf=1&e=IvQYE5)

**Comment by michaldengusiak** [comment] 2019-06-28 14:33
ok tested on Dynamo and got the same issue
![image](https://user-images.githubusercontent.com/26113670/60349732-106c2380-99ba-11e9-88eb-72179070f2d3.png)

**Comment by FraserGreenroyd** [comment] 2019-06-28 18:13
Test script is incorrect, I need the XML file itself, not the GH/Dynamo script please

**Comment by FraserGreenroyd** [comment] 2019-06-28 18:19
I have taken a review, I am able to successfully pull levels from a gbXML file. All levels are pulled successfully. File I tested on had 4 levels, 4 levels are pulled into BHoM.

This is where I'll now need the XML file itself that you're using. I suspect, being built by a topologic workflow rather than the standard workflow, that the XML file itself is incorrect, and thus returning incorrect level data for you. Please provide me the XML file so I can examine whether that is the case on Monday :smile:

![image](https://user-images.githubusercontent.com/18049174/60362661-7025f700-99d9-11e9-9306-46a6a4167aa2.png)

**Comment by michaldengusiak** [comment] 2019-06-28 18:51
ok I added gbXMLs files...from BHoM and Revit,  this is nothing to do with topologic, 
I have this problem when I do normal gbXML export from Revit...using GH or Dynamo script...tested on both...

**Comment by FraserGreenroyd** [comment] 2019-07-01 09:27
I've reviewed the additional XML files and have replicated the original image posted. However, as shown in the below, if you examine the XML file itself (I searched for `<BuildingStorey`) you'll see there are only 2 levels in the XML file, so the toolkit is correctly pulling only 2 levels because only 2 exist to pull :smile:

I'm closing this issue as the functionality is as expected - however if further information comes to light please feel free to reopen this issue or raise a new one :smile:

![image](https://user-images.githubusercontent.com/18049174/60425530-9ff81900-9bea-11e9-8f0d-f39642b5e26e.png)

**Closed by FraserGreenroyd** 2019-07-01 09:27 UTC
Labels: severity:critical, type:bug
