### ISSUE TITLE
XML_Toolkit: Push Error

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#355] opened 2019-09-27 14:09 UTC
#### Description:

Our template does not export anymore
I isolated space with internalize data to help to debug

*I think issues could be tilt bug or doughnut space to be identified

```
1. This component failed to run properly. Are you sure you have the correct type of inputs?
Check their description for more details. Here is the error provided by the method:
Object reference not set to an instance of an object.
```

![image](https://user-images.githubusercontent.com/26113670/65775712-9d00bc00-e138-11e9-938a-891aab1056a9.png)

#### How to replicate:

run script

#### Expected behaviour:

Push gbXML file without errors

#### Test file(s):

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue355_PushError?csf=1&e=UuLrGh)

**Comment by FraserGreenroyd** [comment] 2019-09-30 10:32
Have discussed with @Majalindroth who will pick this up this week.

**Comment by FraserGreenroyd** [comment] 2019-10-03 16:16
Following investigation, this is not a bug with the XML_Toolkit, but is a potential bug within the Geometry Engine. See https://github.com/BHoM/BHoM_Engine/issues/1242 for more details.

To fix the problem when pushing to XML, there are some polylines which are `SelfIntersecting` and should be cleaned prior to the attempt to push to XML.

Closing issue as a non-issue for XML_Toolkit, see issue raised on BHoM_Engine for updates.

**Closed by FraserGreenroyd** 2019-10-03 16:16 UTC
Labels: severity:critical, type:bug
